name: Gradle Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  gradle-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check jacocoTestReport --info --no-daemon --stacktrace
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
