name: Bintray Upload
on:
  release:
    types: [ published ]
jobs:
  bintray-upload:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        with:
          dependencies-cache-enabled: true
          arguments: bintrayUpload